### PR TITLE
Register after_build hook on registration, not after configuration

### PR DESCRIPTION
**Pull request by manuelmeurer**
As discussed here: http://forum.middlemanapp.com/t/order-of-after-build-callbacks/901
It makes sense that all extensions register their after_build hooks immediately when they are activated so the order in which the hooks are executed is the same as the order in which the extensions were activated.
Similar PR here: https://github.com/middleman/middleman-smusher/pull/5
Docs recommend it as well: http://middlemanapp.com/advanced/custom/#toc_9

### CODE REVIEW

**Comment by manuelmeurer** [comment]
Ping! :smiley:

**Comment by karlfreeman** [comment]
Sorry for the delay and thanks for the pointing this out.

**Comment by manuelmeurer** [comment]
Cheers, could you release a new gem version with the fix? Thanks!

**Comment by karlfreeman** [comment]
[Done](https://github.com/karlfreeman/middleman-sync/commit/9363c65865306c70e3a2098db38d4fa46da448e5). :+1:

**Pull request merged**
