### PR TITLE
Make prefix and public_path options configurable

### PR DESCRIPTION
**Pull request by jeremyruppel**
Right now, I can't configure the `prefix` or `public_path` options because they will always get overwritten in the `after_configuration` block. This patch simply sets the defaults _before_ yielding the config.

### CODE REVIEW

**Comment by rossta** [comment]
I was just about to start a pull request myself before I saw this. It'd be great to get this merged in.

**Comment by karlfreeman** [comment]
Dropped the ball on this one, @jeremyruppel thanks for the patch and @rossta thanks for the prompt!

**Comment by karlfreeman** [comment]
As an FYI I've been pushing hard on a project to replace asset_sync called [multi_sync](https://github.com/karlfreeman/multi_sync) Will hopefully have a patch for middleman-sync that not only will be multi-threaded but alot more configurable.

**Comment by rossta** [comment]
Just a note, after trying this change out locally: I believe it depends on middleman-core 3.1+. Got an error when using middleman-core 3.0.14 related to d2d50c3.

**Comment by karlfreeman** [comment]
Just looking into that now. Thanks for the heads up.

**Comment by karlfreeman** [comment]
Give `3.0.11` a go https://github.com/karlfreeman/middleman-sync/commit/964e6f6753fb020e0dcb0b869e97cd2178896d27

**Comment by rossta** [comment]
Cool, thanks. I can confirm that `3.0.11` worked for me on top of both `middleman-3.0.14` and `middleman-3.1.4`

**Comment by karlfreeman** [comment]
@rossta :+1:

**Pull request merged**
